#!/bin/bash

lan_names="enp0s20f0u4u1 enp0s31f6"

if [[ $1 == *$lan_names* ]]; then
    case "$2" in
        up) 
            nmcli radio wifi off 
            ;;  
        down)
            nmcli radio wifi on
            ;;  
    esac
fi

